package com.example.quizzy

object Constants {
    const val TOTAL_QUESTIONS: String = "total_questions"
    const val CORRECT_ANSWERS: String = "correct_answers"
    const val CATEGORY: String = "category"

    fun getQuestions(category: String): ArrayList<Question> {
        val allQuestions = getAllQuestions()
        val filteredQuestions = ArrayList<Question>()
        for (q in allQuestions) {
            if (q.category == category) {
                filteredQuestions.add(q)
            }
        }
        return filteredQuestions
    }

    fun getAllQuestions(): ArrayList<Question> {
        val questionsList = ArrayList<Question>()

        // --- GEOGRAPHY (10 questions) ---
        questionsList.add(Question(1, "Which country has the largest land area?", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/1200px-Flag_of_Russia.svg.png", "Canada", "China", "USA", "Russia", 4, "Geography"))
        questionsList.add(Question(2, "What is the capital of France?", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Paris_Eiffel_Tower_from_the_Trocadero.jpg/1200px-Paris_Eiffel_Tower_from_the_Trocadero.jpg", "London", "Berlin", "Paris", "Madrid", 3, "Geography"))
        questionsList.add(Question(3, "Which is the largest ocean on Earth?", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Clouds_over_the_Atlantic_Ocean.jpg/1200px-Clouds_over_the_Atlantic_Ocean.jpg", "Atlantic", "Indian", "Arctic", "Pacific", 4, "Geography"))
        questionsList.add(Question(4, "What is the smallest country in the world?", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/St_Peter%27s_Square%2C_Vatican_City_-_April_2007.jpg/1200px-St_Peter%27s_Square%2C_Vatican_City_-_April_2007.jpg", "Monaco", "Malta", "Vatican City", "San Marino", 3, "Geography"))
        questionsList.add(Question(5, "Which river flows through Egypt?", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Nile_River_and_Delta_at_night.jpg/1200px-Nile_River_and_Delta_at_night.jpg", "Amazon", "Nile", "Yangtze", "Mississippi", 2, "Geography"))
        questionsList.add(Question(6, "Which continent is known as the 'Dark Continent'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Africa_%28orthographic_projection%29.svg/1200px-Africa_%28orthographic_projection%29.svg.png", "Asia", "South America", "Africa", "Australia", 3, "Geography"))
        questionsList.add(Question(7, "What is the capital of Italy?", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Colosseum_in_Rome-27527.jpg/1200px-Colosseum_in_Rome-27527.jpg", "Milan", "Venice", "Florence", "Rome", 3, "Geography"))
        questionsList.add(Question(8, "Which country is also a continent?", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Australia_%28orthographic_projection%29.svg/1200px-Australia_%28orthographic_projection%29.svg.png", "Australia", "Greenland", "Antarctica", "Iceland", 1, "Geography"))
        questionsList.add(Question(9, "What is the highest mountain in the world?", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Mount_Everest_as_seen_from_Drukair2_PL.jpg/1200px-Mount_Everest_as_seen_from_Drukair2_PL.jpg", "K2", "Mount Everest", "Kilimanjaro", "Mont Blanc", 2, "Geography"))
        questionsList.add(Question(10, "In which country is the Great Barrier Reef?", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Great_Barrier_Reef_from_space.jpg/1200px-Great_Barrier_Reef_from_space.jpg", "Brazil", "Indonesia", "Australia", "Thailand", 3, "Geography"))

        // --- SCIENCE (10 questions) ---
        questionsList.add(Question(11, "Which planet is known as the Red Planet?", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/OSIRIS_Mars_true_color.jpg/1200px-OSIRIS_Mars_true_color.jpg", "Venus", "Mars", "Jupiter", "Saturn", 2, "Science"))
        questionsList.add(Question(12, "What is the chemical symbol for water?", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Water_drop_impact_on_a_water-surface_-_%281%29.jpg/1200px-Water_drop_impact_on_a_water-surface_-_%281%29.jpg", "CO2", "O2", "H2O", "HO2", 3, "Science"))
        questionsList.add(Question(13, "What is the hardest natural substance?", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Rough_diamond.jpg/1200px-Rough_diamond.jpg", "Gold", "Iron", "Diamond", "Quartz", 3, "Science"))
        questionsList.add(Question(14, "Who developed the theory of relativity?", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/1200px-Albert_Einstein_Head.jpg", "Newton", "Tesla", "Einstein", "Galileo", 3, "Science"))
        questionsList.add(Question(15, "What gas do plants absorb from the atmosphere?", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Arancione_foglie.jpg/1200px-Arancione_foglie.jpg", "Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen", 3, "Science"))
        questionsList.add(Question(16, "What is the center of an atom called?", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Stylised_Lithium_Atom.svg/1200px-Stylised_Lithium_Atom.svg.png", "Electron", "Nucleus", "Proton", "Neutron", 2, "Science"))
        questionsList.add(Question(17, "How many planets are in our solar system?", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Planets2013.jpg/1200px-Planets2013.jpg", "7", "8", "9", "10", 2, "Science"))
        questionsList.add(Question(18, "What is the main gas found in the air we breathe?", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Sky_Atmosphere.jpg/1200px-Sky_Atmosphere.jpg", "Oxygen", "Carbon Dioxide", "Nitrogen", "Argon", 3, "Science"))
        questionsList.add(Question(19, "Which unit is used to measure electrical resistance?", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Ohm_symbol.svg/1200px-Ohm_symbol.svg.png", "Volt", "Ampere", "Watt", "Ohm", 4, "Science"))
        questionsList.add(Question(20, "What is the closest star to Earth?", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg/1200px-The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg", "Sirius", "Alpha Centauri", "The Sun", "Betelgeuse", 3, "Science"))

        // --- HISTORY (10 questions) ---
        questionsList.add(Question(21, "In which year did WWII end?", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Victory_Day_in_Moscow.jpg/1200px-Victory_Day_in_Moscow.jpg", "1943", "1944", "1945", "1946", 3, "History"))
        questionsList.add(Question(22, "Who was the first President of the USA?", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg/1200px-Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg", "Lincoln", "Jefferson", "Washington", "Adams", 3, "History"))
        questionsList.add(Question(23, "Which civilization built the pyramids of Giza?", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/1200px-All_Gizah_Pyramids.jpg", "Romans", "Greeks", "Egyptians", "Mayans", 3, "History"))
        questionsList.add(Question(24, "In which year did the Titanic sink?", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/RMS_Titanic_3.jpg/1200px-RMS_Titanic_3.jpg", "1910", "1912", "1914", "1916", 2, "History"))
        questionsList.add(Question(25, "Who discovered America in 1492?", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Sebastian_del_Piombo_-_Portrait_of_a_Man_-_WGA21111.jpg/1200px-Sebastian_del_Piombo_-_Portrait_of_a_Man_-_WGA21111.jpg", "Magellan", "Columbus", "Vasco da Gama", "Cook", 2, "History"))
        questionsList.add(Question(26, "Which country was divided into East and West until 1990?", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Berlin_Wall_at_Bethaniendamm_%281986%29.jpg/1200px-Berlin_Wall_at_Bethaniendamm_%281986%29.jpg", "Korea", "Vietnam", "Germany", "Yemen", 3, "History"))
        questionsList.add(Question(27, "Who was the French queen who was beheaded during the Revolution?", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Marie_Antoinette_Adult4.jpg/1200px-Marie_Antoinette_Adult4.jpg", "Marie Antoinette", "Joan of Arc", "Catherine de Medici", "Anne of Austria", 1, "History"))
        questionsList.add(Question(28, "The Renaissance began in which country?", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Florence_as_seen_from_Michelangelo_Square.jpg/1200px-Florence_as_seen_from_Michelangelo_Square.jpg", "France", "England", "Italy", "Spain", 3, "History"))
        questionsList.add(Question(29, "Who was the leader of Nazi Germany?", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Bundesarchiv_Bild_183-S33882%2C_Adolf_Hitler_retouched.jpg/1200px-Bundesarchiv_Bild_183-S33882%2C_Adolf_Hitler_retouched.jpg", "Mussolini", "Stalin", "Hitler", "Churchill", 3, "History"))
        questionsList.add(Question(30, "The Magna Carta was signed in which year?", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg/1200px-Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg", "1215", "1066", "1492", "1776", 1, "History"))

        // --- ART (10 questions) ---
        questionsList.add(Question(31, "Who painted the Mona Lisa?", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/1200px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg", "Van Gogh", "Picasso", "Da Vinci", "Monet", 3, "Art"))
        questionsList.add(Question(32, "Who painted the 'Starry Night'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1200px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg", "Van Gogh", "Dalí", "Rembrandt", "Warhol", 1, "Art"))
        questionsList.add(Question(33, "Who sculpted the statue of 'David'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/David_by_Michelangelo_Fir_m_copy.jpg/1200px-David_by_Michelangelo_Fir_m_copy.jpg", "Michelangelo", "Donatello", "Bernini", "Rodin", 1, "Art"))
        questionsList.add(Question(34, "Which art movement is Salvador Dalí associated with?", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Salvador_Dali_NYWTS.jpg/1200px-Salvador_Dali_NYWTS.jpg", "Impressionism", "Cubism", "Surrealism", "Pop Art", 3, "Art"))
        questionsList.add(Question(35, "Who painted 'The Last Supper'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Ultima_Cena_-_Da_Vinci_5.jpg/1200px-Ultima_Cena_-_Da_Vinci_5.jpg", "Raphael", "Da Vinci", "Botticelli", "Titian", 2, "Art"))
        questionsList.add(Question(36, "Pablo Picasso is famous for which art style?", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Pablo_picasso_1.jpg/1200px-Pablo_picasso_1.jpg", "Realism", "Abstract", "Cubism", "Expressionism", 3, "Art"))
        questionsList.add(Question(37, "Who painted 'The Scream'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/The_Scream.jpg/1200px-The_Scream.jpg", "Edvard Munch", "Gustav Klimt", "Frida Kahlo", "Henri Matisse", 1, "Art"))
        questionsList.add(Question(38, "Which artist cut off his own ear?", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/1200px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg", "Gauguin", "Van Gogh", "Manet", "Degas", 2, "Art"))
        questionsList.add(Question(39, "Who painted 'The Birth of Venus'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project.jpg/1200px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project.jpg", "Botticelli", "Michelangelo", "Raphael", "Leonardo", 1, "Art"))
        questionsList.add(Question(40, "Where is the Louvre museum located?", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/1200px-Louvre_Museum_Wikimedia_Commons.jpg", "Rome", "London", "Paris", "New York", 3, "Art"))

        // --- SPORTS (10 questions) ---
        questionsList.add(Question(41, "Which country won the 2022 World Cup?", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1200px-Flag_of_Argentina.svg.png", "France", "Brazil", "Argentina", "Germany", 3, "Sports"))
        questionsList.add(Question(42, "How many players are on a soccer team on the field?", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Football_in_Bloomington%2C_Indiana%2C_1996.jpg/1200px-Football_in_Bloomington%2C_Indiana%2C_1996.jpg", "10", "11", "12", "13", 2, "Sports"))
        questionsList.add(Question(43, "Which sport uses the term 'Home Run'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Edwin_Encarnacion_swinging.jpg/1200px-Edwin_Encarnacion_swinging.jpg", "Cricket", "Tennis", "Baseball", "Golf", 3, "Sports"))
        questionsList.add(Question(44, "Who has won the most Olympic gold medals ever?", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Michael_Phelps_Rio_2016.jpg/1200px-Michael_Phelps_Rio_2016.jpg", "Usain Bolt", "Michael Phelps", "Simone Biles", "Serena Williams", 2, "Sports"))
        questionsList.add(Question(45, "Which tennis player is known as the 'King of Clay'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Rafael_Nadal_at_the_2011_French_Open.jpg/1200px-Rafael_Nadal_at_the_2011_French_Open.jpg", "Roger Federer", "Rafael Nadal", "Novak Djokovic", "Andy Murray", 2, "Sports"))
        questionsList.add(Question(46, "In which city were the first modern Olympics held?", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Panathenaic_Stadium_in_Athens.jpg/1200px-Panathenaic_Stadium_in_Athens.jpg", "Rome", "Athens", "Paris", "London", 2, "Sports"))
        questionsList.add(Question(47, "Which sport is played at Wimbledon?", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Wimbledon_Centre_Court_2010.jpg/1200px-Wimbledon_Centre_Court_2010.jpg", "Golf", "Cricket", "Tennis", "Badminton", 3, "Sports"))
        questionsList.add(Question(48, "What is the length of a marathon?", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Boston_Marathon_2010_-_runners.jpg/1200px-Boston_Marathon_2010_-_runners.jpg", "21 km", "42 km", "50 km", "100 km", 2, "Sports"))
        questionsList.add(Question(49, "Which team has the most NBA championships?", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Boston_Celtics_logo.svg/1200px-Boston_Celtics_logo.svg.png", "Lakers", "Bulls", "Warriors", "Celtics", 4, "Sports"))
        questionsList.add(Question(50, "What is the highest possible score in a single frame of bowling?", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Bowling_Pins.jpg/1200px-Bowling_Pins.jpg", "10", "20", "30", "300", 3, "Sports"))

        // --- MOVIES (10 questions) ---
        questionsList.add(Question(51, "Which movie features the character 'Simba'?", "https://upload.wikimedia.org/wikipedia/en/thumb/3/3d/The_Lion_King_poster.jpg/220px-The_Lion_King_poster.jpg", "Aladdin", "Frozen", "The Lion King", "Shrek", 3, "Movies"))
        questionsList.add(Question(52, "Who directed 'Jurassic Park'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Steven_Spielberg_by_Gage_Skidmore.jpg/1200px-Steven_Spielberg_by_Gage_Skidmore.jpg", "George Lucas", "James Cameron", "Steven Spielberg", "Christopher Nolan", 3, "Movies"))
        questionsList.add(Question(53, "Which actor plays Iron Man?", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Robert_Downey%2C_Jr._SDCC_2014_%28cropped%29.jpg/1200px-Robert_Downey%2C_Jr._SDCC_2014_%28cropped%29.jpg", "Chris Evans", "Tom Holland", "Robert Downey Jr.", "Mark Ruffalo", 3, "Movies"))
        questionsList.add(Question(54, "What was the first feature-length animated movie?", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Snow_White_1937_trailer_screenshot_%283%29.jpg/1200px-Snow_White_1937_trailer_screenshot_%283%29.jpg", "Pinocchio", "Bambi", "Snow White", "Dumbo", 3, "Movies"))
        questionsList.add(Question(55, "Which film won the first Oscar for Best Picture?", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Wings_1927_poster.jpg/1200px-Wings_1927_poster.jpg", "Wings", "Sunrise", "Metropolis", "The Jazz Singer", 1, "Movies"))
        questionsList.add(Question(56, "Who played Jack in 'Titanic'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Leonardo_DiCaprio_2014.jpg/1200px-Leonardo_DiCaprio_2014.jpg", "Brad Pitt", "Tom Cruise", "Leonardo DiCaprio", "Johnny Depp", 3, "Movies"))
        questionsList.add(Question(57, "Which movie series features 'The One Ring'?", "https://upload.wikimedia.org/wikipedia/en/thumb/d/d9/Lord_of_the_Rings_The_Fellowship_of_the_Ring_%282001%29_theatrical_poster.jpg/220px-Lord_of_the_Rings_The_Fellowship_of_the_Ring_%282001%29_theatrical_poster.jpg", "Star Wars", "Harry Potter", "Lord of the Rings", "The Chronicles of Narnia", 3, "Movies"))
        questionsList.add(Question(58, "What is the name of the kingdom in 'Frozen'?", "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Frozen_%282013_film%29_poster.jpg/220px-Frozen_%282013_film%29_poster.jpg", "Arendelle", "Genovia", "Far Far Away", "Atlantis", 1, "Movies"))
        questionsList.add(Question(59, "Who directed 'Inception'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Christopher_Nolan_Cannes_2018.jpg/1200px-Christopher_Nolan_Cannes_2018.jpg", "Quentin Tarantino", "Christopher Nolan", "Martin Scorsese", "Ridley Scott", 2, "Movies"))
        questionsList.add(Question(60, "Which film is highest-grossing of all time?", "https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/Avatar-Teaser-Poster.jpg/220px-Avatar-Teaser-Poster.jpg", "Avengers: Endgame", "Titanic", "Avatar", "Star Wars: Force Awakens", 3, "Movies"))

        // --- MUSIC (10 questions) ---
        questionsList.add(Question(61, "Who is known as the King of Pop?", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Michael_Jackson_in_1984.jpg/1200px-Michael_Jackson_in_1984.jpg", "Prince", "Michael Jackson", "Elvis Presley", "Madonna", 2, "Music"))
        questionsList.add(Question(62, "How many members were in the Beatles?", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/The_Fabs.JPG/1200px-The_Fabs.JPG", "3", "4", "5", "6", 2, "Music"))
        questionsList.add(Question(63, "Which instrument has 88 keys?", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Steinway_%26_Sons_Model_D_274_concerto_grand_piano.jpg/1200px-Steinway_%26_Sons_Model_D_274_concerto_grand_piano.jpg", "Guitar", "Violin", "Piano", "Harp", 3, "Music"))
        questionsList.add(Question(64, "Who composed the 'Fifth Symphony'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Beethoven.jpg/1200px-Beethoven.jpg", "Mozart", "Bach", "Beethoven", "Chopin", 3, "Music"))
        questionsList.add(Question(65, "Who was the lead singer of Queen?", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Freddie_Mercury_performing_in_New_Haven%2C_CT%2C_November_1977.jpg/1200px-Freddie_Mercury_performing_in_New_Haven%2C_CT%2C_November_1977.jpg", "Freddie Mercury", "Mick Jagger", "David Bowie", "Robert Plant", 1, "Music"))
        questionsList.add(Question(66, "What genre of music is Bob Marley famous for?", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Bob-Marley-in-Concert_Zurich_05-30-80.jpg/1200px-Bob-Marley-in-Concert_Zurich_05-30-80.jpg", "Jazz", "Blues", "Reggae", "Rock", 3, "Music"))
        questionsList.add(Question(67, "Who is the 'Queen of Soul'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Aretha_Franklin_1968.jpg/1200px-Aretha_Franklin_1968.jpg", "Beyoncé", "Whitney Houston", "Aretha Franklin", "Tina Turner", 3, "Music"))
        questionsList.add(Question(68, "Which band released 'The Dark Side of the Moon'?", "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/Dark_Side_of_the_Moon.png/220px-Dark_Side_of_the_Moon.png", "Led Zeppelin", "Pink Floyd", "The Rolling Stones", "The Who", 2, "Music"))
        questionsList.add(Question(69, "Who is the youngest artist to win Album of the Year at the Grammys?", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Billie_Eilish_2019_by_Glenn_Francis.jpg/1200px-Billie_Eilish_2019_by_Glenn_Francis.jpg", "Taylor Swift", "Adele", "Billie Eilish", "Harry Styles", 3, "Music"))
        questionsList.add(Question(70, "What is the stage name of Marshall Mathers?", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Eminem_live_at_Glasgow_Summer_Sessions_2017.jpg/1200px-Eminem_live_at_Glasgow_Summer_Sessions_2017.jpg", "Snoop Dogg", "Jay-Z", "Eminem", "Dr. Dre", 3, "Music"))

        // --- LITERATURE (10 questions) ---
        questionsList.add(Question(71, "Who wrote 'Romeo and Juliet'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Shakespeare.jpg/1200px-Shakespeare.jpg", "Dickens", "Shakespeare", "Twain", "Austen", 2, "Literature"))
        questionsList.add(Question(72, "Who wrote the 'Harry Potter' series?", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/1200px-J._K._Rowling_2010.jpg", "Tolkien", "Lewis", "Rowling", "Dahl", 3, "Literature"))
        questionsList.add(Question(73, "Who created Sherlock Holmes?", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Arthur_Conan_Doyle_by_Walter_Boughton_1914.jpg/1200px-Arthur_Conan_Doyle_by_Walter_Boughton_1914.jpg", "Agatha Christie", "Arthur Conan Doyle", "Edgar Allan Poe", "Stephen King", 2, "Literature"))
        questionsList.add(Question(74, "Who wrote '1984'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/George_Orwell_press_photo.jpg/1200px-George_Orwell_press_photo.jpg", "George Orwell", "Aldous Huxley", "Ray Bradbury", "H.G. Wells", 1, "Literature"))
        questionsList.add(Question(75, "Who wrote 'The Great Gatsby'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/F_Scott_Fitzgerald_1921.jpg/1200px-F_Scott_Fitzgerald_1921.jpg", "Hemingway", "Fitzgerald", "Faulkner", "Steinbeck", 2, "Literature"))
        questionsList.add(Question(76, "Who wrote 'Pride and Prejudice'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Jane_Austen_coloured_version.jpg/1200px-Jane_Austen_coloured_version.jpg", "Jane Austen", "Charlotte Brontë", "Emily Brontë", "Mary Shelley", 1, "Literature"))
        questionsList.add(Question(77, "Who wrote 'The Odyssey'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Homer_British_Museum.jpg/1200px-Homer_British_Museum.jpg", "Socrates", "Plato", "Homer", "Aristotle", 3, "Literature"))
        questionsList.add(Question(78, "Who wrote 'Don Quixote'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Cervantes_Miguel_de_Velasquez.jpg/1200px-Cervantes_Miguel_de_Velasquez.jpg", "Cervantes", "Dante", "Machiavelli", "Goethe", 1, "Literature"))
        questionsList.add(Question(79, "Who wrote 'Frankenstein'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Mary_Shelley_by_Richard_Rothwell.jpg/1200px-Mary_Shelley_by_Richard_Rothwell.jpg", "Mary Shelley", "Bram Stoker", "Oscar Wilde", "Victor Hugo", 1, "Literature"))
        questionsList.add(Question(80, "Who wrote 'The Hobbit'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/J._R._R._Tolkien%2C_ca._1925.jpg/1200px-J._R._R._Tolkien%2C_ca._1925.jpg", "C.S. Lewis", "J.R.R. Tolkien", "Roald Dahl", "George R.R. Martin", 2, "Literature"))

        // --- NATURE (10 questions) ---
        questionsList.add(Question(81, "What is the largest mammal in the world?", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Blue_Whale_underwater.jpg/1200px-Blue_Whale_underwater.jpg", "Elephant", "Blue Whale", "Giraffe", "Shark", 2, "Nature"))
        questionsList.add(Question(82, "Which bird is the only one that can fly backwards?", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Hummingbird_in_flight.jpg/1200px-Hummingbird_in_flight.jpg", "Eagles", "Hummingbird", "Owl", "Parrot", 2, "Nature"))
        questionsList.add(Question(83, "What is a group of lions called?", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Lion_waiting_in_Namibia.jpg/1200px-Lion_waiting_in_Namibia.jpg", "Pack", "Herd", "Pride", "Flock", 3, "Nature"))
        questionsList.add(Question(84, "What is the fastest land animal?", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Cheetah_%28Acinonyx_jubatus%29_female_2.jpg/1200px-Cheetah_%28Acinonyx_jubatus%29_female_2.jpg", "Lion", "Tiger", "Cheetah", "Horse", 3, "Nature"))
        questionsList.add(Question(85, "What is the largest species of shark?", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Whale_shark_Georgia_aquarium.jpg/1200px-Whale_shark_Georgia_aquarium.jpg", "Great White", "Hammerhead", "Whale Shark", "Tiger Shark", 3, "Nature"))
        questionsList.add(Question(86, "What is the national animal of India?", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Walking_tiger_female.jpg/1200px-Walking_tiger_female.jpg", "Elephant", "Lion", "Bengal Tiger", "Peacock", 3, "Nature"))
        questionsList.add(Question(87, "How many stages are there in a butterfly's life cycle?", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Monarch_Butterfly_Danaus_plexippus_Male_3000px.jpg/1200px-Monarch_Butterfly_Danaus_plexippus_Male_3000px.jpg", "2", "3", "4", "5", 3, "Nature"))
        questionsList.add(Question(88, "What do bees collect from flowers to make honey?", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Apis_mellifera_Western_honey_bee.jpg/1200px-Apis_mellifera_Western_honey_bee.jpg", "Pollen", "Nectar", "Leaves", "Sap", 2, "Nature"))
        questionsList.add(Question(89, "Which animal is known as the 'Ship of the Desert'?", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/07._Camel_Profile%2C_Near_Silverton%2C_NSW%2C_07.07.2007.jpg/1200px-07._Camel_Profile%2C_Near_Silverton%2C_NSW%2C_07.07.2007.jpg", "Camel", "Horse", "Donkey", "Elephant", 1, "Nature"))
        questionsList.add(Question(90, "What is the tallest animal in the world?", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Giraffe_Mikumi_National_Park.jpg/1200px-Giraffe_Mikumi_National_Park.jpg", "Elephant", "Ostrich", "Giraffe", "Moose", 3, "Nature"))

        // --- TECHNOLOGY (10 questions) ---
        questionsList.add(Question(91, "Who co-founded Apple?", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Steve_Jobs_Headshot_2010-edit2.jpg/1200px-Steve_Jobs_Headshot_2010-edit2.jpg", "Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Elon Musk", 2, "Technology"))
        questionsList.add(Question(92, "What does 'CPU' stand for?", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Intel_Core_i7_Haswell_top.jpg/1200px-Intel_Core_i7_Haswell_top.jpg", "Computer Power Unit", "Central Processing Unit", "Core Process Unit", "Control Power Unit", 2, "Technology"))
        questionsList.add(Question(93, "Who is the founder of Facebook?", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg/1200px-Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg", "Steve Jobs", "Jeff Bezos", "Mark Zuckerberg", "Larry Page", 3, "Technology"))
        questionsList.add(Question(94, "Which company owns the Android OS?", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Android_robot.svg/1200px-Android_robot.svg.png", "Apple", "Microsoft", "Google", "Samsung", 3, "Technology"))
        questionsList.add(Question(95, "What is the main programming language for Android?", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Kotlin-logo.svg/1200px-Kotlin-logo.svg.png", "Swift", "Kotlin", "Python", "C#", 2, "Technology"))
        questionsList.add(Question(96, "What does 'WWW' stand for?", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/WWW_logo.svg/1200px-WWW_logo.svg.png", "World Wide Web", "Web Wide World", "Western World Web", "Whole Wide Web", 1, "Technology"))
        questionsList.add(Question(97, "In which year was the first iPhone released?", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/IPhone_2G_PSD_v2.png/1200px-IPhone_2G_PSD_v2.png", "2005", "2007", "2008", "2010", 2, "Technology"))
        questionsList.add(Question(98, "Who is the founder of Tesla and SpaceX?", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg/1200px-Elon_Musk_Royal_Society_%28crop2%29.jpg", "Jeff Bezos", "Bill Gates", "Elon Musk", "Tim Cook", 3, "Technology"))
        questionsList.add(Question(99, "What is the most popular search engine?", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png", "Bing", "Yahoo", "Google", "DuckDuckGo", 3, "Technology"))
        questionsList.add(Question(100, "What was the name of the first programmable computer?", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Eniac.jpg/1200px-Eniac.jpg", "ENIAC", "IBM-PC", "Apple I", "Commodore 64", 1, "Technology"))

        return questionsList
    }
}
